# Generated by Django 5.1.2 on 2024-10-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
